/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims.gui;

import ims.bll.InfoBLL;
import ims.dto.Infomation;
import ims.dto.dantoc;
import ims.dto.giadinh;
import ims.dto.gioitinh;
import ims.dto.honnhan;
import ims.dto.khoa;
import ims.dto.namtotnghiep;
import ims.dto.nganh;
import ims.dto.nghe;
import ims.dto.noidaotao;
import ims.dto.quoctich;
import ims.dto.thanhpho;
import ims.dto.tongiao;
import ims.dto.trinhdodaotao;
import ims.dto.xeploai;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NAT
 */
public class Employee extends javax.swing.JFrame {

    InfoBLL infobll = new InfoBLL();
    InfoBLL gioitinhBLL = new InfoBLL();
    InfoBLL dantocBLL = new InfoBLL();
    InfoBLL giadinhbll = new InfoBLL();
    InfoBLL honnhanbll = new InfoBLL();
    InfoBLL khoabll = new InfoBLL();
    InfoBLL nambll = new InfoBLL();
    InfoBLL nganhbll = new InfoBLL();
    InfoBLL nghebll = new InfoBLL();
    InfoBLL noidaotaobll = new InfoBLL();
    InfoBLL quoctichbll = new InfoBLL();
    InfoBLL thanhphobll = new InfoBLL();
    InfoBLL tongiaobll = new InfoBLL();
    InfoBLL trinhdobll = new InfoBLL();
    InfoBLL xeploaibll = new InfoBLL();
    Infomation inf = new Infomation();
    InfoBLL addNew = new InfoBLL();
    String maNV;
    
    /**
     * Creates new form Employee
     */
    public SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");
    
    private Infomation infoma;
   
    public Employee() {
        initComponents();
         setInfoDialog();  
    }

    Employee(String maNV) {
        this.maNV = maNV;
        initComponents();
        setInfoDialog();
        
    }
   
    public  void setInfoDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);        
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHovaDem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHovaten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMachamcong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNoisinh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNguyenquan = new javax.swing.JTextField();
        txtHinh = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNoicap = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSohochieu = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNoicapHC = new javax.swing.JTextField();
        cbTThonnhan = new javax.swing.JComboBox<>();
        cbTPgiadinh = new javax.swing.JComboBox<>();
        cbDantoc = new javax.swing.JComboBox<>();
        cbTongiao = new javax.swing.JComboBox<>();
        cbQuoctich = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        dNgaycapcmnd = new com.toedter.calendar.JDateChooser();
        dNgaycaphc = new com.toedter.calendar.JDateChooser();
        dNgayhethanhc = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtTrinhdovanhoa = new javax.swing.JTextField();
        cbTrinhdodaotao = new javax.swing.JComboBox<>();
        cbNoidaotao = new javax.swing.JComboBox<>();
        cbKhoadaotao = new javax.swing.JComboBox<>();
        cbChuyennganh = new javax.swing.JComboBox<>();
        cbXeploai = new javax.swing.JComboBox<>();
        cbNghenghiep = new javax.swing.JComboBox<>();
        cbNamtotnghiep = new javax.swing.JComboBox<>();
        cbTP = new javax.swing.JComboBox<>();
        cbGioitinh = new javax.swing.JComboBox<>();
        btHuy = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        dNgaysinh = new com.toedter.calendar.JDateChooser();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Mã N.Viên");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setText("Họ và đệm");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setText("Họ và tên");

        jLabel4.setText("Mã chấm công");

        jLabel6.setText("Tên");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setText("Ngày sinh");

        jLabel8.setText("Giới tính");

        jLabel9.setText("Nơi sinh");

        jLabel10.setText("Nguyên quán");

        txtHinh.setBackground(new java.awt.Color(240, 240, 240));
        txtHinh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHinh.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Số CMND");

        jLabel12.setText("Ngày cấp");

        jLabel13.setText("Nơi cấp CMND");

        jLabel14.setText("Số hộ chiếu");

        jLabel15.setText("Ngày cấp");

        jLabel16.setText("Ngày hết hạn");

        jLabel17.setText("TT hôn nhân");

        jLabel18.setText("TP Gia đình");

        jLabel19.setText("Dân tộc");

        jLabel20.setText("Tôn giáo");

        jLabel21.setText("Quốc tịch");

        jLabel22.setText("Nơi câp HC");

        jButton1.setText("...");

        jButton2.setText("...");

        jButton3.setText("...");

        jButton4.setText("...");

        jButton5.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dNgaycaphc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dNgayhethanhc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNoicapHC, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTThonnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cbTPgiadinh, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cbDantoc, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cbTongiao, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cbQuoctich, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCMND)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dNgaycapcmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addComponent(txtNoicap, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSohochieu, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dNgaycapcmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoicap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSohochieu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dNgayhethanhc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addComponent(dNgaycaphc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNoicapHC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTThonnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTPgiadinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDantoc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTongiao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbQuoctich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setText("Trình độ văn hóa");

        jLabel24.setText("Trình độ đào tạo");

        jLabel25.setText("Nơi đào tạo");

        jLabel26.setText("Khoa đào tạo");

        jLabel27.setText("Chuyên ngành");

        jLabel28.setText("Năm tốt nghiệp");

        jLabel29.setText("Xếp loại");

        jLabel30.setText("Nghề nghiệp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbXeploai, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChuyennganh, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKhoadaotao, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNoidaotao, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrinhdovanhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTrinhdodaotao, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNghenghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNamtotnghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrinhdovanhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTrinhdodaotao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNoidaotao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKhoadaotao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChuyennganh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(cbNamtotnghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbXeploai, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNghenghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btHuy.setText("Hủy");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        btSave.setText("Ghi");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNguyenquan, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtHovaten, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtHovaDem, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel4)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMachamcong, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                                            .addComponent(txtTen)))
                                    .addComponent(txtNoisinh, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10)
                                .addComponent(txtHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSave)
                .addGap(42, 42, 42)
                .addComponent(btHuy)
                .addGap(363, 363, 363))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMachamcong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHovaDem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNguyenquan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbTP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHuy)
                    .addComponent(btSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        // TODO add your handling code here:
        EmployeeList e = new EmployeeList();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_btHuyActionPerformed

    public void setInfomation (Infomation infomation) {
        this.infoma = infoma;
        txtMaNV.setText(String.valueOf(infomation.getMaNV()));
        txtMachamcong.setText(String.valueOf(infomation.getMaCC()));
        txtHovaDem.setText(infomation.getHovadem());
        txtTen.setText(infomation.getTen());
        txtHovaten.setText(infomation.getHovaten());
        dNgaysinh.setDateFormatString(infomation.getNgaysinh());
        cbGioitinh.setSelectedItem(infomation.getGioitinh());
        txtNoisinh.setText(infomation.getNoisinh());
        txtNguyenquan.setText(infomation.getNguyenquan());
        txtCMND.setText(infomation.getCmnd());
        dNgaycapcmnd.setDateFormatString(infomation.getNgaycap());
        cbTThonnhan.setSelectedItem(infomation.getHonnhan());
        cbTPgiadinh.setSelectedItem(infomation.getGiadinh());
        cbDantoc.setSelectedItem(infomation.getDantoc());
        cbTongiao.setSelectedItem(infomation.getTongiao());
        cbQuoctich.setSelectedItem(infomation.getQuoctich());
        txtTrinhdovanhoa.setText(infomation.getVanhoa());
        cbTrinhdodaotao.setSelectedItem(infomation.getDaotao());
        cbNoidaotao.setSelectedItem(infomation.getNoidaotao());
        cbKhoadaotao.setSelectedItem(infomation.getKhoa());
        cbChuyennganh.setSelectedItem(infomation.getNganh());
        cbNamtotnghiep.setSelectedItem(infomation.getNamtotnghiep());
        cbXeploai.setSelectedItem(infomation.getXeploai());
        cbNghenghiep.setSelectedItem(infomation.getNghe());
    }
    
    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        java.util.Date NgaySinh = dNgaysinh.getDate();
        String ngaysinh = dateFormat.format(NgaySinh);
        java.util.Date NgayCap = dNgaycapcmnd.getDate();
        String ngaycap = dateFormat.format(NgayCap);
        java.util.Date NgayCapHC = dNgaycaphc.getDate();
        String ngaycaphc = dateFormat.format(NgayCapHC);
        java.util.Date NgayHetHan = dNgayhethanhc.getDate();
        String ngayhethan = dateFormat.format(NgayHetHan);
        
        stateButton(true);
        String maNV = txtMaNV.getText();
        String maCC = txtMachamcong.getText();
        String hovadem = txtHovaDem.getText();
        String hovaten = txtHovaten.getText();
        String ten = txtTen.getText();
        String gioitinh = cbGioitinh.getSelectedItem().toString();
        String noisinh = txtNoisinh.getText();
        String nguyenquan = txtNguyenquan.getText();
        String thanhpho = cbTP.getSelectedItem().toString();
        String cmnd = txtCMND.getText();
        String noicap = txtNoicap.getText();
        String sohc = txtSohochieu.getText();
        String noicaphc = txtNoicapHC.getText();
        String honnhan = cbTThonnhan.getSelectedItem().toString();
        String giadinh = cbTPgiadinh.getSelectedItem().toString();
        String dantoc = cbDantoc.getSelectedItem().toString();
        String tongiao = cbTongiao.getSelectedItem().toString();
        String quoctich = cbQuoctich.getSelectedItem().toString();
        String vanhoa = txtTrinhdovanhoa.getText();
        String trinhdo = cbTrinhdodaotao.getSelectedItem().toString();
        String noidaotao = cbNoidaotao.getSelectedItem().toString();
        String khoa = cbKhoadaotao.getSelectedItem().toString();
        String nganh = cbChuyennganh.getSelectedItem().toString();
        String namtotnghiep = cbNamtotnghiep.getSelectedItem().toString();
        String xeploai = cbXeploai.getSelectedItem().toString();
        String nghe = cbNghenghiep.getSelectedItem().toString();
        
        inf.setMaNV(Integer.parseInt(maNV));
        inf.setMaCC(Integer.parseInt(maCC));
        inf.setHovadem(hovadem);
        inf.setHovaten(hovaten);
        inf.setTen(ten);  
        inf.setNgaysinh(ngaysinh);
        inf.setGioitinh(gioitinh);
        inf.setNoisinh(noisinh);
        inf.setNguyenquan(nguyenquan);
        inf.setCmnd(cmnd);
        inf.setNgaycap(ngaycap);
        inf.setNoicapcmnd(noicap);
        inf.setSohc(sohc);
        inf.setNgaycaphc(ngaycaphc);
        inf.setNgayhethanhc(ngayhethan);
        inf.setNoicaphc(noicaphc);
        inf.setHonnhan(honnhan);
        inf.setGiadinh(giadinh);
        inf.setDantoc(dantoc);
        inf.setTongiao(tongiao);
        inf.setQuoctich(quoctich);
        inf.setVanhoa(vanhoa);
        inf.setDaotao(trinhdo);
        inf.setNoidaotao(noidaotao);
        inf.setKhoa(khoa);
        inf.setNganh(nganh);
        inf.setNamtotnghiep(Integer.parseInt(namtotnghiep));
        inf.setXeploai(xeploai);
        inf.setNghe(nghe);
        inf.setThanhpho(thanhpho);
        addNew.addNewBLL(inf);
        
        if(hovaten.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Họ và tên.");
            txtHovaten.requestFocus();
        }
        if(ten.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên.");
            txtTen.requestFocus();
        }
        if(cmnd.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số CMND.");
            txtCMND.requestFocus();
        }
        if(maNV.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã nhân viên.");
            txtMaNV.requestFocus();
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultComboBoxModel modelGT = (DefaultComboBoxModel)cbGioitinh.getModel();
        ArrayList<gioitinh> gtListModel = gioitinhBLL.readGTBLL();
        gioitinh gioitinhModel = new gioitinh();
        for(int i = 0; i< gtListModel.size();i++){
            gioitinhModel = gtListModel.get(i);
            modelGT.addElement(gioitinhModel.getLoaiGT());
        }
        gtListModel.clear();
        
        DefaultComboBoxModel modelDT = (DefaultComboBoxModel)cbDantoc.getModel();
        ArrayList<dantoc> dtListModel = dantocBLL.readDTBLL();
        dantoc dantocModel = new dantoc();
        for(int i = 0; i< dtListModel.size();i++){
            dantocModel = dtListModel.get(i);
            modelDT.addElement(dantocModel.getTenDT());
        }
        dtListModel.clear();
        
        DefaultComboBoxModel modelGD = (DefaultComboBoxModel)cbTPgiadinh.getModel();
        ArrayList<giadinh> gdListModel = giadinhbll.readGDBLL();
        giadinh giadinhModel = new giadinh();
        for(int i = 0; i< gdListModel.size();i++){
            giadinhModel = gdListModel.get(i);
            modelGD.addElement(giadinhModel.getLoaiGD());
        }
        gdListModel.clear();
        
        DefaultComboBoxModel modelHN = (DefaultComboBoxModel)cbTThonnhan.getModel();
        ArrayList<honnhan> hnListModel = honnhanbll.readHNBLL();
        honnhan honnhanModel = new honnhan();
        for(int i = 0; i< hnListModel.size();i++){
            honnhanModel = hnListModel.get(i);
            modelHN.addElement(honnhanModel.getLoaiHN());
        }
        hnListModel.clear();
        
        DefaultComboBoxModel modelKhoa = (DefaultComboBoxModel)cbKhoadaotao.getModel();
        ArrayList<khoa> khoaListModel = khoabll.readKhoaBLL();
        khoa khoaModel = new khoa();
        for(int i = 0; i< khoaListModel.size();i++){
            khoaModel = khoaListModel.get(i);
            modelKhoa.addElement(khoaModel.getTenKhoa());
        }
        khoaListModel.clear();
        
        DefaultComboBoxModel modelNam = (DefaultComboBoxModel)cbNamtotnghiep.getModel();
        ArrayList<namtotnghiep> namListModel = nambll.readNamBLL();
        namtotnghiep namModel = new namtotnghiep();
        for(int i = 0; i< namListModel.size();i++){
            namModel = namListModel.get(i);
            modelNam.addElement(namModel.getNam());
        }
        namListModel.clear();
        
        DefaultComboBoxModel modelNganh = (DefaultComboBoxModel)cbChuyennganh.getModel();
        ArrayList<nganh> nganhListModel = nganhbll.readNganhBLL();
        nganh nganhModel = new nganh();
        for(int i = 0; i< nganhListModel.size();i++){
            nganhModel = nganhListModel.get(i);
            modelNganh.addElement(nganhModel.getTenNganh());
        }
        nganhListModel.clear();
        
        DefaultComboBoxModel modelNghe = (DefaultComboBoxModel)cbNghenghiep.getModel();
        ArrayList<nghe> ngheListModel = nghebll.readNgheBLL();
        nghe ngheModel = new nghe();
        for(int i = 0; i< ngheListModel.size();i++){
            ngheModel = ngheListModel.get(i);
            modelNghe.addElement(ngheModel.getTenNghe());
        }
        ngheListModel.clear();
        
        DefaultComboBoxModel modelNoidaotao = (DefaultComboBoxModel)cbNoidaotao.getModel();
        ArrayList<noidaotao> ndtListModel = noidaotaobll.readNDTBLL();
        noidaotao ndtModel = new noidaotao();
        for(int i = 0; i< ndtListModel.size();i++){
            ndtModel = ndtListModel.get(i);
            modelNoidaotao.addElement(ndtModel.getTenNoidaotao());
        }
        ndtListModel.clear();
        
        DefaultComboBoxModel modelQuoctich = (DefaultComboBoxModel)cbQuoctich.getModel();
        ArrayList<quoctich> qtListModel = quoctichbll.readQTBLL();
        quoctich qtModel = new quoctich();
        for(int i = 0; i< qtListModel.size();i++){
            qtModel = qtListModel.get(i);
            modelQuoctich.addElement(qtModel.getTenQT());
        }
        qtListModel.clear();
        
        DefaultComboBoxModel modelThanhpho = (DefaultComboBoxModel)cbTP.getModel();
        ArrayList<thanhpho> tpListModel = thanhphobll.readTPBLL();
        thanhpho tpModel = new thanhpho();
        for(int i = 0; i< tpListModel.size();i++){
            tpModel = tpListModel.get(i);
            modelThanhpho.addElement(tpModel.getTenTP());
        }
        tpListModel.clear();
        
        DefaultComboBoxModel modelTongiao = (DefaultComboBoxModel)cbTongiao.getModel();
        ArrayList<tongiao> tgListModel = tongiaobll.readTGBLL();
        tongiao tgModel = new tongiao();
        for(int i = 0; i< tgListModel.size();i++){
            tgModel = tgListModel.get(i);
            modelTongiao.addElement(tgModel.getTenTG());
        }
        tgListModel.clear();
        
        DefaultComboBoxModel modelTrinhdodaotao = (DefaultComboBoxModel)cbTrinhdodaotao.getModel();
        ArrayList<trinhdodaotao> tdListModel = trinhdobll.readTDBLL();
        trinhdodaotao tdModel = new trinhdodaotao();
        for(int i = 0; i< tdListModel.size();i++){
            tdModel = tdListModel.get(i);
            modelTrinhdodaotao.addElement(tdModel.getTen());
        }
        tdListModel.clear();
        
        DefaultComboBoxModel modelXeploai = (DefaultComboBoxModel)cbXeploai.getModel();
        ArrayList<xeploai> xlListModel = xeploaibll.readXLBLL();
        xeploai xlModel = new xeploai();
        for(int i = 0; i< xlListModel.size();i++){
            xlModel = xlListModel.get(i);
            modelXeploai.addElement(xlModel.getLoai());
        }
        xlListModel.clear();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btSave;
    public javax.swing.JComboBox<String> cbChuyennganh;
    public javax.swing.JComboBox<String> cbDantoc;
    public javax.swing.JComboBox<String> cbGioitinh;
    public javax.swing.JComboBox<String> cbKhoadaotao;
    public javax.swing.JComboBox<String> cbNamtotnghiep;
    public javax.swing.JComboBox<String> cbNghenghiep;
    public javax.swing.JComboBox<String> cbNoidaotao;
    public javax.swing.JComboBox<String> cbQuoctich;
    public javax.swing.JComboBox<String> cbTP;
    public javax.swing.JComboBox<String> cbTPgiadinh;
    public javax.swing.JComboBox<String> cbTThonnhan;
    public javax.swing.JComboBox<String> cbTongiao;
    public javax.swing.JComboBox<String> cbTrinhdodaotao;
    public javax.swing.JComboBox<String> cbXeploai;
    public com.toedter.calendar.JDateChooser dNgaycapcmnd;
    public com.toedter.calendar.JDateChooser dNgaycaphc;
    public com.toedter.calendar.JDateChooser dNgayhethanhc;
    public com.toedter.calendar.JDateChooser dNgaysinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtHinh;
    public javax.swing.JTextField txtHovaDem;
    public javax.swing.JTextField txtHovaten;
    public javax.swing.JTextField txtMaNV;
    public javax.swing.JTextField txtMachamcong;
    public javax.swing.JTextField txtNguyenquan;
    public javax.swing.JTextField txtNoicap;
    public javax.swing.JTextField txtNoicapHC;
    public javax.swing.JTextField txtNoisinh;
    public javax.swing.JTextField txtSohochieu;
    public javax.swing.JTextField txtTen;
    public javax.swing.JTextField txtTrinhdovanhoa;
    // End of variables declaration//GEN-END:variables

    private void stateButton(boolean value) {
        btSave.setVisible(value);
        btHuy.setVisible(value);
    }           
}
